### ISSUE TITLE
Add support for @language annotation

### ISSUE THREAD

**Issue by simoami** [acuminous/yadda#102]
It would be great to add support for language annotation so that each feature file can identify its own language and parsing can be detect the source language automatically. This eliminates the guess work and doesn't force all features to be parsed against a single language setting.

Ref: http://docs.behat.org/guides/1.gherkin.html#gherkin-in-many-languages

**Comment by cressie176** [comment]
Turned out to be difficult to do this automatically or by an annotation since the FeatureParser. Instead I've added the ability to change the default language by setting ```Yadda.localisation.default```, e.g.
```js
Yadda.localisation.default = Yadda.localisation.Pirate;
```
I also considered allowing this to be set using an environment variable but decided against it since Yadda can be used in the browser.

**Comment by simoami** [comment]
np, thanks for giving it a shot.
