### ISSUE TITLE
Is there a way to include fragments (or complete .feature files) to a .feature file?

### ISSUE THREAD

**Issue by brunobasto** [acuminous/yadda#149]
It's more like a question than an issue. Some parts of my tests can be reused. And I'd like to reuse them. 

Imagine that I'm testing a feature that takes an user to sign up, login, navigate to specific part of the application and then I'm on the part that I want to test. Wouldn't it be nice to be able to just do something like:

    #include navigate_to_control_panel.feature

and then I could just worry about my tests in the control panel:

    Scenario: Test some control panel feature
       Given I'm in control panel
       When I do something
       Then I expect something to happen

**Comment by cressie176** [comment]
There are a couple of ways to achieve this, but they may not be as elegant as you would wish. The first is to use a background, which works well providing

1. You don't need to share backgrounds across features
2. You want the background to run for every scenario in the feature
3. You want the background to run before the scenarios.

The syntax is

```bdd
Background: Navigate to control panel

   Sign up
   Login
   Navigate to some page

Scenario:
   
   When I do something
   Then I expect something to happen
```

If you can't use backgrounds then here's what I've done in the past

```bdd
Scenario:
   Given I'm in control panel
```

```js
library.given("I'm in control panel", function(next) {
   async.series([signUp(aNewUser), loginIn(aNewUser), visitPage('some'), next)
}
```

Although I've never tried it, It should also be possible to invoke yadda from a step (i.e. like the film inception).

```js
// Assuming you run your tests with mocha
var Yadda = require('yadda');
Yadda.plugins.mocha.StepLevelPlugin.init();

new Yadda.FeatureFileSearch('features').each(function(file) {

    featureFile(file, function(feature) {

        var library = require('./bottles-library');
        var yadda = Yadda.createInstance(library);

        scenarios(feature.scenarios, function(scenario) {
            var ctx = { yadda: yadda };
            steps(scenario.steps, function(step, done) {
                yadda.run(step, done);
            });
        });
    });
});
```

```js
library.given("I'm in control panel", function(next) {
   this.yadda.run(['sign up', 'login', 'Navigate to some page'], next)
}
```

There's a [discussion](https://github.com/acuminous/yadda/issues/27) around re-usable scenarios here. It's a difficult feature to implement without making the specifications less readable (the whole point of bdd). Maybe if the third option works it isn't even necessary.

**Comment by cressie176** [comment]
I added an example for creating reusable fragments. It could be made nicer by using a template loaded from the file system, rather than creating the scenario in code.

Also because the fragment isn't run directly from mocha, you only get one line of output for the entire scenario rather than the individual steps, i.e.

```
  Reusable Scenario Example
    100 green bottles
      ✓ Sing 100 green bottles are standing on the wall 
    100 blue bottles
      ✓ Sing 100 blue bottles are standing on the wall 
```

**Comment by ami44** [comment]
thank  :+1:

**Comment by cressie176** [comment]
@brunobasto OK to close?

**Comment by brunobasto** [comment]
@cressie176 

Sure. Thank you very much for such detailed answers. I think I'll go with backgrounds for now. Just as an FYI, this is how I'm currently doing it:

I have some .feature files, and I want to be able to execute some of them always before the others (the login case. Users should be able to login first and then I can carry on with my tests). What I did was to put and underscore before the name of the file so that it is alwasy the first file to be executed by yadda:

    _login.feature
    testControlPanelA.feature
    testControlPAnelB.feature

Would be able to define some kind of order of execution from within the language. I can do it in my end by looking for scenarios that have some annotation like @Before and run them first and then the others. That brings another question: Do you currently support annotations for the feature definition or only for scenario definition?

I'm thinking it would be something like this:

    @Before
    Feature: Log in
        As an user
        I should be able to log in

And then I can do something like:

    files.forEach(function(file, i, files) {
        featureFile(file, function(feature) {
            if (feature.annotations.before) {
                // run the before tests before
            }
        });
    });

**Comment by brunobasto** [comment]
Just so that you can understand better, the reason I'm doing it is because I want to be able to share background across features. The login background is one that many features would want to use.

**Comment by cressie176** [comment]
> Do you currently support annotations for the feature definition or only for scenario definition?

You can annotate features and scenarios but not backgrounds

One way to implement the @Before annotation is to write your own version of [FeatureFileSearch](https://github.com/acuminous/yadda/blob/master/lib/FeatureFileSearch.js) which sorted the based on your the @Before annotation.  However by coupling features you'll be splitting your scenarios across multiple files which makes them less coherent. 

I tend to setup some a common set of users and duplicate the backgrounds in multiple feature files.

```bdd
Background: 
   Given Amy is a logged in admin
   and Uriah is a logged in user
   and Gerald is not logged in

Scenario: Logged in admins have full access to the control panel
   When Amy navigates to the control panel
   then she can access widget X
   and she can access widget Y   

Scenario: Logged in users have restricted access to the control panel
   When Uriah navigates to the control panel
   he can access widget X
   but cannot access widget Y

Scenario: Guests have no access to the control panel
   When Gerald navigates to the control panel
   he is instructed to login
```

**Comment by brunobasto** [comment]
Awesome. The main reason that I want to separate and reuse the login set of actions is because it takes quite a few clicks to login and go to control panel. I want to avoid duplication.

Thank you, you've been very helpful. I think I have more information now than I ever expected :)

Feel free to close this issue.

**Comment by lolmaus** [comment]
I have one use case for multiple features per file.

Very often I have a feature which has a number of scenarios, which don't share a single `Background`.

For example, a `Posts` feature would have scenarios that require posts to already exist. It is very conveinent to put seeding of those posts into the `Background`.

But then there are `Posts` scenarios that need to have no posts seeded: viewing an empty feed, accessing a non-existing post, creating first post, etc.

Those scenarios cannot be put under the same `Background` as other `Posts` scenarios.

There are two workarounds:
* Remove `Background` and instead put the seeding into each scenario that requires it. That will cause a lot of code duplication, viloating DRY, and blow up the feature file.
* Split the feature file in two. That lets you conform to DRY, but now a single feature is represented by two feature files.

Both workarounds are sub-optimal. I believe, having two `Feature`s in one file, each with its own `Background`, would be the lesser of evils.

**Comment by cressie176** [comment]
Hi @lolmaus,

If I understand correctly you would like something like mocha's `describe` feature which allows you to nest blocks of tests within tests, and allow block specific `before` scripts. e.g.

```
Feature: Create User

  Feature: User pre-exists
    Background:
      Given a user called "Fred Bloggs", with email "fred@example.com" and username "freddy99"
     
      Scenario: Prevent duplicate email addresses
        When I register a user called "John Smith", with email "fred@example.com" and username "johnny99"
        Then registration fails because a user with that email address already exists

      Scenario: Prevent duplicate usernames
        When I register a user called "John Smith", with email "john@example.com" and username "freddy99"
        Then registration fails because a user with that username already exists

      Scenario: Allow duplicate names
        When I register a user called "Fred Bloggs", with email "john@example.com" and username "johnny99"
        Then registration succeeds
   
    Feature: New User

        When I register a user called "Fred Bloggs", with email "john@example.com" and username "johnny99"
        Then registration succeeds
```

This is not something I am interested in supporting with Yadda. Just because in the POST example, one level of nesting is sufficient, in other situations people might want deeper nesting. I don't think the additional complexity is worth it. I would solve the above by replicating the Given statement

```
Feature: Create User

  Scenario: Prevent duplicate email addresses
    Given a user called "Fred Bloggs", with email "fred@example.com" and username "freddy99"      
    When I register a user called "John Smith", with email "fred@example.com" and username "johnny99"
    Then registration fails because a user with that email address already exists

  Scenario: Prevent duplicate usernames
    Given a user called "Fred Bloggs", with email "fred@example.com" and username "freddy99"  
    When I register a user called "John Smith", with email "john@example.com" and username "freddy99"
    Then registration fails because a user with that username already exists

  Scenario: Allow duplicate names
    Given a user called "Fred Bloggs", with email "fred@example.com" and username "freddy99"  
    When I register a user called "Fred Bloggs", with email "john@example.com" and username "johnny99"
    Then registration succeeds

  Scenario: Unique user
    When I register a user called "Fred Bloggs", with email "john@example.com" and username "johnny99"
    Then registration succeeds
```

You're right, this means repeating the `Given` step, and is therefore a violation of the DRY principle. However, despite being a worthy cause, DRY is not the only consideration. Whenever you factor out duplication you increase coupling and indirection. The former increases brittleness and the latter reduces coherence. For so little gain, I'm not willing to consider complicating the feature parser to support nested features.

That said, the feature parser is pluggable, so you are able to write your own version that supports nested feature files if you so wish. A simple version would flatten the result into a single list and should work from then on. I suspect you could also write your own mocha plugin which mapped nested features to `describe` calls in order to get nested test output (assuming you're using mocha of course)

**Comment by lolmaus** [comment]
> If I understand correctly you would like something like mocha's describe feature

I didn't mean nested `Feature`s, just multiple `Feature`s per file.

> You're right, this means repeating the Given step

This is how typical seeding looks in projects I work on: https://gist.github.com/lolmaus/d56f10788e9d9c4553b2ff368d0e7078

Repeating all of that is much more painful than repeating a single `Given` line.

**Comment by cressie176** [comment]
> I didn't mean nested Features, just multiple Features per file.

Thanks for the clarification. I understand now that you do not want nesting. However the features are related, which is how come you want to physically group them in the same file. I'm uneasy with this direction, as the obvious next step would be to logically group them. At which point you have nesting.

Thanks also for supplying the gist. When scenarios need complex test fixtures I tend to create a single step, either using random or pre-canned data e.g.
```
Given a typical product catalog
```
or perhaps
```
Given a catalog of 8 random products
```
or even
```
Given a catalog of 8 random products
Including a product X
```
And thus reduce the setup steps to a small number of lines.

```
Feature

Scenario: 
  Given a catalog of 8 random products
  Including a product X
  When I request the product list
  Then all 8 products are returned
  Ordered alphabetically by product name
  And including product X
```

I find adding large amounts of fixture setup to the BDD scenarios invariably reduces clarity and is best avoided.

However there's still nothing to stop you implementing multi-feature files yourself. Just split the features before passing them to the FeatureParser.

I'm pretty sure the the [mocha plugin](https://github.com/acuminous/yadda/blob/bd3b74b72bcecdcf2ffa9937b6d0cbc1a36ce03d/lib/plugins/mocha/BasePlugin.js#L16-L20) will work with an array of features, just as well as it works with a single one.

**Comment by lolmaus** [comment]
Thx for looking into this and giving it a consideration!

I'm not insisting that you implement multiple features per file. I'm just chiming in to give this feature request a broader picture.

> When scenarios need complex test fixtures I tend to create a single step

We've had really bad experience with this approach, to a point of rejecting Cucumber at all.

One problem is that the scenario becomes incoherent. E. g.:

```feature
Given a catalog of 8 random products
Then the third product should have a price of 300
```

By looking at this scenario, it is impossible to tell if it's valid or not. Why is the price 300 and not 200?

Another problem is that those multi-seeding steps end up being reused. This should be a good thing, but it's not! The matter is that different scenarios have slightly different requirements, and each developer is contributing to the reusable step, adding more stuff to satisfy the requirements of the feature they are working on.

As a result, a stemp `Given a catalog of $number random products` produces:
* product with comments
* product without comments
* product with variants
* product with a single variant
* product in stock
* product out of stock
* product with likes
* product without likes
* product with japanese characters (failing case for bug 23156)
etc, this can go on forever

At certain point, this step becomes enormous, a god step. Scenarios get seeded excessive amounts of data, becoming slow and very difficult to maintain. There's too much going on.

It also made it very difficult to contribute to existing tests. A change in one place can break stuff in another place, making developers avoid refactorings as much as possible.

To resolve this problem, I went with a radical approach: move all the truth to the feature file. Steps are atomic, single-responsibility, and make no assumptions about the business logic. 

This approach also let me have explicit references in steps titles, thanks to all the ids and slugs being exposed in the `Background` section. As a result, I was able to stop using `this.ctx` entirely, which substantially reduced the complexity of tests by removing implicit dependencies and obscure behavior.

Additionally, I've developed a system of "labels": strictly semantic, human readable DOM references which are converted to HTML selectors. This let me drastically reduce the amount of step implementations. We no longer have ad-hoc steps, all steps are entirely generic and fully reusable.

Readability suffered a bit, e. g. instead of `When I request the product list` we would write `When I click the Request-List-Button`, and instead of `Then all 8 products are returned` we'd say `Then there should be 8 Products in the Product-List`.

The latter step would do something like `assert.equal(document.querySelectorAll('[data-test-product-list] [data-test-product]').length, 8)`.

Though a bit less readable, it stays understandable to non-developers!

Another benefit is that the steps are now explicit. By reading a step, you know *exactly* what it does, no guesswork needed. There are no false-positive caused by people responsible for step validation *assuming* that steps do what they are supposed to do.

A small, reusable step library means that all developers are familiar with it, they no longer need to browse hundeds of steps in frustration, searching for relevant ones, they no longer need to painfully decypher step implementation code to see what steps *actually do*, and they no longer end up implement duplicate steps when they fail to locate an existing one.

**Comment by cressie176** [comment]
> I'm not insisting that you implement multiple features per file. I'm just chiming in to give this feature request a broader picture.

Understood, and always happy to discuss. One of my biggest lessons from writing Yadda, is that I didn't keep the focus tight enough. The more that's added, the less malleable the software tends to  become. Things aren't too bad, but it's still something I'm conscious of, and so very reluctant to add features that I don't think are needed, or that bend Yadda's raison d'être.

> By looking at this scenario, it is impossible to tell if it's valid or not. Why is the price 300 and not 200?

I completely agree with you on this. I think it's important only assert on things what are present in the scenario / test. For the same reason I think it's important not to dilute those things with a lot of necessary, but distracting setup. My preferred approach is to generate random fixtures, then override just the parts salient to the tests. Hence the example

```
Scenario: List product catalog
  Given a catalog of 8 random products
  Including a product X
  When I request the product list
  Then all 8 products are returned
  Ordered alphabetically by product name
  And including product X
```

> At certain point, this step becomes enormous, a god step. Scenarios get seeded excessive amounts of data, becoming slow and very difficult to maintain. There's too much going on.

I also agree this is a concern, and something you need to work hard against. It's also part of the motivation behind Yadda. I often write fine grained steps that build up complex data over a number of statements

```
Given a typical hospital
With a male patient called Fred
Who was admitted with a cardiovascular condition
And placed on a female, respiratory ward
When I view the bed management dashboard
Confirm Fred's status is off-template
```

The salient items are still very much in the feature file, with the advantage that they aren't diluted by information the test doesn't care about.

> Readability suffered a bit, e. g. instead of When I request the product list we would write When I click the Request-List-Button, and instead of Then all 8 products are returned we'd say Then there should be 8 Products in the Product-List.
>
> Additionally, I've developed a system of "labels": strictly semantic, human readable DOM references which are converted to HTML selectors. This let me drastically reduce the amount of step implementations. We no longer have ad-hoc steps, all steps are entirely generic and fully reusable.

Interestingly I try to do the opposite. I don't want DOM elements appearing in my BDD tests, and even try to re-use the same feature file in frontend and restful tests, by loading a different set of step implementations. I achieve generic step definitions by extracting variables from the step text and mapping them to data/css/id attributes and/or url paths. e.g.

| Step Text | Step Pattern | Result |
|-----------|-------------|------|
| When I view the bed management dashboard | When I view the $name | GET /bed-management-dashboard |
| Confirm Fred's status is off-template | Confirm $patientName $locator is $value | SELECT `<div class="status" data-patient-id: "12345">off-tempate</div>` |

I use Yadda's dictionary feature to map patient name to a patient behind the scenes.

**Comment by lolmaus** [comment]
> > By looking at this scenario, it is impossible to tell if it's valid or not. Why is the price 300 and not 200?
> 
> My preferred approach is to generate random fixtures, then override just the parts salient to the tests. Hence the example
>
> ```feature
> Given a catalog of 8 random products
> Including a product X
> ```

This is an example of an implicit dependency that I would very much like to avoid.

In an artificial example it seems fine, but real-life cases typically much more complicated.

And I want to be specific. Instead of `And including product X`, I would like to go through all products and ensure they all have correct properties.

You also seem to be creating lots of ad-hoc steps. This makes test very readable and concise, but for me this approach made development very slow, and maintenance painful.

Step implementations should be covered with tests, otherwise there is no guarantee that every step is doing what you think it's doing. For example, `And including product X` can be doing something entirely different, e. g. asserting a product with name `X` exists on the page, but not necessarily in the Product List being tested.

Or that step implementation could be entirely empty! You'll not be able to tell.

This is especially painful when multiple developers are writing tests, and each has their own unique style. I've seen very elaborate systems using the context, e. g. `And including product X` would expect the list to be in `this.ctx.productList`. I've seen steps changing their meaning depending on their order. I've seen conflicts.

I look at a concise, purely human-oriented scenario — and I see a Gordian knot.

<details>
  <summary>GIF time!</summary>

![keep talking and nobody explodes](https://user-images.githubusercontent.com/200884/82363653-cc8d6d00-9a16-11ea-92b5-0dc386b9aa73.png)

![sweat](https://i.imgur.com/gInovKi.gif)
</details>

With a small library of reusable steps representing simple user actions, creating new acceptance tests is quick and effortless. It does not require writing a line of JS. Just add semanting `data-test-*` attributes to HTML and compose feature files out of a few dozen steps.

**Comment by lolmaus** [comment]
> Interestingly I try to do the opposite. I don't want DOM elements or even UI controls referenced directly in my BDD tests

Though you achieve perfect BDD readability, those feature files mean nothing by themselves.

I can't tell what your feature is really doing without studying test implmentations.

My steps are atomic instructions. A scenario a program that can be executed by both machine and human, including non-developers. You look through steps and you know *exactly* what happens, without having to look inside each step. No guesswork, no assumptions, no false positives.

**Comment by lolmaus** [comment]
PS I know my tone may seem harsh, like a pressing argument. This is not my intention!

Yadda is my most favorite developer tool.

I remember seeing Yadda for the first time back in 2015. I was like wow, these guys have their stuff figured out! I should give it a try!

At that moment, I didn't know that I would owe Yadda my current — amazing! — job position at @kaliber5.

I'm now building an addon for the EmberJS framework which is gonna provide a highly opinionated and highly efficient take on Yadda.

And I enjoy this discussion so much. I don't see it as an argument (I'm sorry if my manner makes it feel this way), but rather as sharing experience!

**Comment by cressie176** [comment]
> And I enjoy this discussion so much. I don't see it as an argument (I'm sorry if my manner makes it feel this way), but rather as sharing experience!

Completely agree. No worries from me.

> In an artificial example it seems fine, but real-life cases typically much more complicated.

This is how I've developed applications for years, and in fact recently published [yup-by-example](https://github.com/cressie176/yup-by-example) to make it easier. I've found the approach (not yup-by-example - still too new) exceptionally useful for generating complex fixtures, while keeping tests streamlined. As I'm sure you're aware TDD isn't just about ensuring software works, it's also about design (less so once those principles have taken hold), providing a regression test suite so you can make changes safely, communication and motivation. 

I agree that having extensive, highly explicit tests offers the greatest assurance that the software works, but at the cost of communication and potentially increased maintenance when something changes. I prefer an approach that balances communication and robustness with a reasonable degree of assurance for the types of applications I work on.

> You also seem to be creating lots of ad-hoc steps. This makes test very readable and concise, but for me this approach made development very slow, and maintenance painful.

I've tended to use this approach with teams of 4-8 experienced developers with lots of pairing and pair rotation and never had a problem, however I've also had other people express similar concerns when I've described how I prefer to use Yadda. It's also a long time since I've worked on a team that wrote web tests and we generally only use BDD where the business logic is complicated, and more traditional unit testing for everything else.

> Step implementations should themselves be covered with tests, otherwise there is no guarantee that every step is doing what you think it's doing

I strongly disagree that you should write tests for step implementations in anything but the most critical / high governance systems. The returns just aren't worth it. 

> Though you achieve perfect BDD readability, those feature files mean nothing by themselves.

They express the desired behaviour of the system in a way that is decoupled from technology. I've worked on some systems with unavoidably complicated business logic. Expressing this in the relevant domain language is valuable even if you never write the underlying step implementations. However you're [not alone](https://web.archive.org/web/20161224222716/http://blog.punchbarrel.com/2013/06/13/functional-testing-bdd-and-domain-specific-languages/) in this opinion. 

> This also looks lovely, linking the business terminology to concrete program actions in a nice simple manner. However, this apparent simplicity hides the fact that the textual step name has no actual relationship to the concrete code. Sure, the text is used in at least two places, so it seems as if the system is on the case to prevent typos and accidental mis-edits, but it still says nothing about what the step code actually does.

Despite this truism, In practice, I find the business requirements are expressed in a clear way, and the step implementations do what I expect them to do.

Glad you're enjoying working at @kaliber5.. They website's very nice. Good luck with the Ember add on too.
