### ISSUE TITLE
Support for Timeout modification

### ISSUE THREAD

**Issue by Ashthos** [acuminous/yadda#193]
Hi

I am automating protractor (angular/brower/selenium) tests using yadda. Some steps in the tests can take so long that we hit the Jasmine.DEFAULT_TIMEOUT value (1 minute). Jasmine supports specifying the timeout applied to an individual 'it' call. 

https://github.com/jasmine/jasmine/commit/68ba5b6d48624c063b4eeae1bdd63c5aa84a3177

Can yadda also support this in some way? I can see complexity in how the timeout would need to be specified per 'it' as this probably should not be part of the language used in the steps.

Cheers

**Comment by cressie176** [comment]
That's a fun one, made more difficult because I took a shortcut with the Jasmine plugin. It's really just the mocha plugin since their APIs are so similar.

A solution for now would be to set the default jasmine timeout to something much larger.

Going forward what to you think about specifying the timeout with an annotation at scenario level?

```
@step-timeout=5000
scenario: etc etc
```

This timeout would be applied to all steps. Not perfect, but better than a global and without doing something crazy with the individual steps.

**Comment by Ashthos** [comment]
Its an idea. However my use-case complicates things quite a bit. Let me explain further.

The framework that I have built around Yadda allows steps to contain steps. Meaning that one step in a feature may equate to an limitless number of steps in a hierarchy being executed. Sounds mad I know but it works nicely!

This would mean that it would be more useful to specify a timeout in the step definition `library.given('text', function, timeout)` style. This would allow things like:

- step in .feature file timeout 1 minute
- - step in code timeout 20 seconds
- - - step in hierarchy timeout 1 second
- - - step in hierarchy timeout 2 seconds
- - step in code timeout 30 seconds

This would mean that there is a way of ensuring that steps higher in the hierarchy do not timeout before all their sub steps have executed.

Just to add some different detail, most of my lowest level steps execute sub second, however sometimes they will loop until an html element appears on the screen, which may mean that the step  gets executed 000's of times in quick succession - but all under the guise of the .feature's step.

**Comment by cressie176** [comment]
Yep - that certainly complicates things... 

1. The ```it``` function is called before the step is looked up, so defining a timeout on the step definition isn't going to help
1. Defining a timeout on a step definition reduces the steps reusability - all matching step strings would get the same timeout whether appropriate or not

Have you considered another form of timeout instead of Jasmine? I haven't used protractor but with webdriver you can set a timeout on waitFor commands. Your steps could then be...

```
then the sale is confirmed within 5 seconds
```
and pass the second value from the step variables to the webdriver function?

**Comment by Ashthos** [comment]
I have thought about setting the Jasmine timeout to a very high number, however that is less useful when the consumers of the framework forget to call next() in their steps - the Jasmine timeout is what tends to capture this mistake on the build servers.

I suppose I could wrap the step execution in a timer, which will fire a jasmine.fail() if the default timeout is hit, unless the step code explicitly sets new timeout value. Bit messy, but could work.

**Comment by cressie176** [comment]
I can't think of a better way :( 
https://github.com/sithmel/callback-decorators#timeout might come in handy.

**Comment by cressie176** [comment]
Closing as not much I can do. Sorry
