### ISSUE TITLE
Doc string support

### ISSUE THREAD

**Issue by itsimoshka** [acuminous/yadda#204]
Hi!
Thank you for yadda. It is awesome.
But I miss one thing. 
I am implementing the same features as server-side team(so I can't change features), but there are many DocStrings. And I can't implement it with yadda. 
Can you please add DocStrings support?

**Comment by cressie176** [comment]
No sorry. Yadda already supports multiline steps, which are more readable than docstrings. The whole point of feature files is to be readable, so I don't want add something into the yadda codebase that encourages otherwise.

However, you can write your own FeatureFileParser based on the one that ships with Yadda. I'd imagine you could use the multiline comment code and / or multiline step code as an example.

**Comment by itsimoshka** [comment]
ok, thank you...
