### ISSUE TITLE
Always Getting A Timeout On After All Hook With Cucumber-Boilerplate

### ISSUE THREAD

**Issue by dheeraj1988** [acuminous/yadda#209]
Error Description :

1) "after all" hook:
Error: timeout of 25000ms exceeded. Ensure the done() callback is being called in this test.
at null. (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\mocha\lib\runnable.js:215:19)

I dont see any after all hook in implementation ?

**Comment by cressie176** [comment]
Hi @dheeraj1988,

I think you misunderstand Yadda. It isn't a test runner, and so doesn't have before and after hooks. It's just a library that when given a string, will lookup a function, parse arguments from the string, then execute the function with those arguments.

How you execute Yadda is entirely up to you, but as a convenience I provides integration for common test frameworks such as mocha. If you were to use mocha directly instead of via cucumber boilerplate you could write the before and after functions in the normal way.

Other developers have built libraries on top of Yadda, but aren't linked to the project itself. To me your issue looks related to the [cucumber boilerplate](https://github.com/webdriverio/cucumber-boilerplate) project. If you raise you question there they may be able to help.

I also notice that this is the second time you've posted the same issue to the Yadda project, but you didn't respond to [my previous comments](https://github.com/acuminous/yadda/issues/202). I expect you had reasons, but if possible please respond to any questions or advice within a reasonable time. I close issues where the author doesn't reply.

**Comment by cressie176** [comment]
It's also possible you have code like the following somewhere in your test.

```
after(function(done) {
   // Does not call done()
})
```

**Comment by dheeraj1988** [comment]
Hey thanks for the info. I will get back to you on this soon.

**Comment by cressie176** [comment]
Any luck?

**Comment by dheeraj1988** [comment]
No Luck, Please Close It :(
