### ISSUE TITLE
Different to Gherkin?

### ISSUE THREAD

**Issue by BevanR** [acuminous/yadda#218]
AFAICT Yadda's syntax is the same as Gherkin.  However the [documentation](https://github.com/acuminous/yadda/blob/master/README.md) still states;

> we find Yadda less invasive and prefer it's flexible syntax to Gherkin's. Yadda's conflict resolution is smarter too.

Could you please elaborate on this comment?

**Comment by cressie176** [comment]
Yadda steps are free form, meaning that you don't have to start steps with the words "given", "when" or "then", they can be anything you like.  It's less invasive because you can plug it into your preferred test library (mocha, jasmine, nightwatch, etc). Yadda also has multiple strategies for dealing with conflict resolution (when step text could be satisfied by multiple definitions). These include

1. Allowing you to selectively load step libraries (Cucumber* loaded them all at starting increasing the likelihood of conflicts)
1. Dictionaries encourage more specific patterns without sacrificing readability
1. Scoring matching step definitions using Levenshtein's distance and picking the one most similar to the step text
1. Preferring steps from the last used library when all other factors are equal
1. Reporting unresolvable duplicates (Cucumber* executed the first one it found)



*These problems may since have been resolved - I haven't checked in on Cucumber since writing Yadda.

**Comment by BevanR** [comment]
Cool!

But how does Yadda keep the Gherkin unambiguous from the author's and reader's point of view?

In my experience Gherkin is already plenty flexible, at the cost of being a bit too permissive of ambiguity.  Also, I find the few rules it implies (Given-When-Then) almost enough to encourage useful scenarios almost all of the time.

I personally wouldn't want to introduce more flexibility nor ambiguity.  If anything, I'd want a bit less flexibility.  E.g. Require the same number of `Then` as `When` and always in the order of When-Then.

Should I still consider Yadda?  Why?

**Comment by cressie176** [comment]
> In my experience Gherkin is already plenty flexible, at the cost of being a bit too permissive of ambiguity. Also, I find the few rules it implies (Given-When-Then) almost enough to encourage useful scenarios almost all of the time.

My 2c is that BDD tests get very dull, formulaic and wordy - which kind of defeats the point. 
You're free to stick to G/W/T with Yadda, but it provides the option to make the tests pack more punch when appropriate. 

Yadda certainly introduces more flexibility (IMHO a good thing), and deals with ambiguity far better than Cucumber. If you don't to value flexibility, and don't foresee problems with ambiguous steps or care about the other issues I mentioned, there are still other features (e.g. automated type conversion) in Yadda that weren't in cucumber at time of writing.

**Comment by BevanR** [comment]
Could you elaborate on automated type conversion in Yadda or link to the docs?  I'm not sure how or why this would be useful or broken in Cucumber.

**Comment by cressie176** [comment]
>

**Comment by cressie176** [comment]
OK to close?

**Comment by BevanR** [comment]
Sure!  Thanks very much!  :)
