### ISSUE TITLE
How to run features in parallel?

### ISSUE THREAD

**Issue by iinkov** [acuminous/yadda#240]
Mocha allows run features in parallel by using for example mocha-parallel-tests
I've found that "steps(scenario.steps, function(step, done)" block steps cross whole run
Is it possible to run it parallel by some other way?
Cucumber.js has "--parallel" parameter. Perhaps you have something similar I didn't find

**Comment by cressie176** [comment]
Hi @linkov,
There's nothing native in Yadda to make it run in parallel, but there's nothing stopping it in the core API either. The current mocha plugin is merely a convenience, but you don't need to use it to run tests. e.g. https://github.com/acuminous/yadda/blob/master/examples/basic/demo.js

I suspect you could write a variation of the Mocha plugin (maybe using mocha.parallel) that would parallelise the tests. I think using mocha-parallel-tests might be another alternative, but slightly harder since it seems to work from test files, and with Yadda you usually have only one.

**Comment by iinkov** [comment]
@cressie176 Thx, seems it works. As I get the only reason for Mocha plugin is output of results. And mocha plugin blocks parallelism. So it will be needed to write something for that
