### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by pbarringer3** [acuminous/yadda#282]
Hi, my team uses yadda with mocha for our tests. I've recently been playing around with the idea of parallelizing our tests using worker threads. Would you be open to a pull request implementing this possibility. I would probably end up making this an alternate plugin, something like threadable_mocha.

**Comment by cressie176** [comment]
Hi @pbarringer3,
Happy to consider and discuss. Any reason it needs to be in the Yadda code base rather than a separate package? One of the lessons I've learned from writing yadda, is that I shouldn't have accepted PRs for things like component, bower or karma as I'm not very familiar with these tools and so not well placed to support them. At the very least I'd reference the plugin from the README and user guide.

**Comment by pbarringer3** [comment]
I certainly could do it in a separate package, and will if it doesn't work out to add it to the Yadda code base, but I think it would be more widely used if it was in the base package. I'll get something together and submit a PR.
